alterando quality gate para falhar quando não passar

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -71,8 +71,9 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
           QUALITY_GATE_STATUS=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=lanchonete-fiap_lanchonete-produto" -H "Authorization: Basic $SONAR_TOKEN" | jq -r '.projectStatus.status')
-          if [ "$QUALITY_GATE_STATUS" = "OK" ]; then
-            echo "QG OK"
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "Fail on Quality Gate"
+          exit 1
           fi
 
   push-to-registry:
